apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ulfh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ulfh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ulfh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ulfh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ulfh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nltt-tenant/rhtap-demo-app/hacbs-test-project-ulfh@sha256:dcf52b220bd2fd6c2d129691d26a7df2e05b4856614af91d76a9a62cd31d9f60
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
