apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ulfh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nltt-tenant/rhtap-demo-app/hacbs-test-project-ulfh@sha256:3c50e90ade52e38d4d7e6dafce680cff55c9040b1743cc005b98c542c5c06ffb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
