apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ulfh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nltt-tenant/rhtap-demo-app/hacbs-test-project-ulfh@sha256:dcf52b220bd2fd6c2d129691d26a7df2e05b4856614af91d76a9a62cd31d9f60
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
